
// import Image from 'next/image'
import Header from '../components/Header'
import Feed from '../components/Feed';
import UploadModal from '../components/UploadModal';


// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className='bg-gray-50 min-h-screen'>
      <head>
        <title>Instagram Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
      </head>

      {/* Header */}

      <Header />

      {/* feed */}
      <Feed/>
      
      {/* modal */}
      <UploadModal/>
    </div>
  );
}
